### ISSUE TITLE
[discovery] Font preview text strings 

### ISSUE THREAD

**Issue by pathumego** [fontman/fontman-desktop#20]
For #19. @lpsandaruwan We already have a lots of test strings at hand to go for the alpha. But the actual task is not collecting them but organising them with necessary data. Once we start diggininto #37 we will revisit this, but form now we need to do the following.

- [ ]  define json structure: As we discussed the test and preview text strings has to come from json objects and will come with set of tags and metadata that correspond to `tags`. (ie: When a user select Sinhala language to filter, the test string will switch to Sinhala)
- [ ] Once we have that structure I can start putting together the test strings in that json structure. I would like to keep the sources in yaml and convert that in the build.
- [ ] Text strings for font-box previews #19 
- [ ] Text strings for test compare view #26

**Comment by lpsandaruwan** [comment]
What came to my mind is a YAML structure like this,

```
English:
    - sentence:
        - DJs flock by when MTV ax quiz prog.
        - Vamp fox held quartz duck just by wing.
    - para:
        - Grumpy wizards make toxic brew for the evil Queen and Jack. One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections.
```
